name: Deploy automático na VPS

on:
  push:
    branches:
      - main  # ou a branch que tu quiser

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Fazer build
        run: dotnet publish -c Release -o out

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "out/*"
          target: ${{ secrets.VPS_PATH }}

      - name: Reiniciar servidor remoto
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            pkill -f 'dotnet' || true
            nohup dotnet ./NomeDoTeuProjeto.dll > log.txt 2>&1 &
